### ISSUE TITLE
looking for Inf/NaN vs inf/nan patches for SPARC Solaris 11 gcc 5

### ISSUE THREAD

**Issue by dimpase** [oracle/solaris-userland#1]
At present gcc 5.4.0 shipped by Oracle has a non-standard way of printing Inf and NaN on SPARC Solaris 11.
(see the code below). Could someone please point out to use for  relevant patches (ideally for gcc 7, but the one for gcc 5 would do, too). For some reason they never made it upstream, as far as I can tell.
Thanks!
```
/* inftest.c */
#include <stdio.h>
int main(void)
{
    double val = 10;
    for(int i = 0; i < 10000; ++i) {
        val = val * val;
    }
    printf("%g\n", val);
    printf("%g\n", val-val);
}
/* compile and run (with Oracle's gcc 5.4.0)
  $ gcc inftest.c
  $ ./a.out
  Inf
  NaN
*/
/* with '-std=c99' or '-std=c1x' it works correctly!
  $ gcc -std=c1x inftest.c
  $ ./a.out
  inf
  nan

With vanilla gcc 7.2 there is no difference, it's always Inf/NaN.
*/
```

**Comment by normjacobs** [comment]
FWIW,
The difference in output has to do with how printf(3) works in Solaris libc and how GCC is linking the final binary.  Among other things, libc (and libm) implement support for functions specified in the C and Unix standards.  Because there are slight variations between standards, they use the absence/presence of a few private variables determine the "desired" behavior.  In this particular instance, printf changes behavior based on __xpg6, which comes from /usr/lib/values-xpg6.o.  To better understand the results, 
change your program to declare "i" before your for loop and compile with:
$ gcc -v -o test test.c 2>&1 | grep collect2
$ gcc -v -std=c89 -o test-c89 test.c 2>&1 | grep collect2
$ gcc -v -std=c99 -o test-c99 test.c 2>&1 | grep collect2
Here you will get an idea of how they are linked and you can compare the results of running them and the generated executables.

The specific patch to GCC 5.4.0 that effects this is https://github.com/normjacobs/solaris-userland/blob/master/components/gcc5/patches/002-libc-values.patch

The printf code that corresponds to this should be found in the results of http://src.illumos.org/source/search?q=inf_nan_mixed_case&defs=&refs=&path=&hist=&project=illumos-gate

**Comment by dimpase** [comment]
Thanks. We're working on this here: https://github.com/gap-system/gap/issues/2193

**Comment by rorth** [comment]
Hi Norm,

> The specific patch to GCC 5.4.0 that effects this is
> https://github.com/normjacobs/solaris-userland/blob/master/components/gcc5/patches/002-libc-values.patch

thanks for providing the background.  This is also GCC bug

	PR target/40411
        -std=c99 does not enable c99 mode in Solaris C library
        https://gcc.gnu.org/bugzilla/show_bug.cgi?id=40411

This has now been fixed (finally) for the upcoming GCC 8 release by

	https://gcc.gnu.org/ml/gcc-patches/2018-01/msg01024.html
        https://gcc.gnu.org/ml/gcc-patches/2018-01/msg02384.html

Right now, there's no plan to backport the patches to earlier GCC
releases, but the patch can certainly be applied locally in
solaris-userland.

	Rainer

**Comment by normjacobs** [comment]
Rainer,

Unfortunately, I am no longer with Oracle, so I am unable to integrate an updated patch for the earlier GCC releases in the solaris-userland gate.  I will try to contact the folks now managing the gate to let them know that they should look into updating their GCC patches.  Thanks for getting this addressed in GCC 8.

    -Norm

**Comment by rorth** [comment]
Hi Norm,

> Unfortunately, I am no longer with Oracle, so I am unable to integrate an updated
> patch for the earlier GCC releases in the solaris-userland gate. I will try to contact
> the folks now managing the gate to let them know that they should look into
> updating their GCC patches. Thanks for getting this addressed in GCC 8.

I've learned that some time ago.  I've already informed the guy taking
care of gcc in solaris-userland theses days of the new.

Thanks for getting the ball rolling again on this longstanding issue.

	Rainer

**Comment by vlmarek** [comment]
Hi,

We don't plan to backport this fix to the current version of gcc  (5 and 7) we use. It will be pulled with gcc 8. Because of that I'm closing the issue.

Thank you for the report
__ 
  Vlad
